### ISSUE TITLE
BizTalk SSO Ticket error “Validation of the ticket failed. The sender name must match that of the ticket issuer.”

### ISSUE THREAD

**Issue by Dijkgraaf** [mbrimble/brepipelineframework#3]
If you have a Receive Location on an Isolated host, and you then send to a send port (In-Process Host) and use the Create SSO Ticket rule in the Send Port, then the username and the Ticket don't match.

See https://stackoverflow.com/questions/42387623/biztalk-sso-ticket-error-validation-of-the-ticket-failed-the-sender-name-must

**Comment by mbrimble** [comment]
Closed as this is not an issue as shown by Coen's answer.
