### ISSUE TITLE
Question - Calling Map from C#? 

### ISSUE THREAD

**Issue by NealWalters** [mbrimble/brepipelineframework#6]
This is just a question, not an issue. I understand that you call multiple maps in a pipeline component built with your framework.  Do you call and execute the map from C# then.  Can you point me to the source where you do that? 

Thanks,
Neal Walters

**Comment by RobBowman** [comment]
Hi Neal, Ahmed describes map chaining in this video: [integration monday video](http://www.integrationusergroup.com/unravel-bre-pipeline-framework-powerful-features-for-building-biztalk-messaging-solutions/ )

**Comment by NealWalters** [comment]
I was actually just looking for a code sample, because I want to call a map in my C# program.  Trying to batch regression test 100s of maps on an upgrade.  Sorry if I didn't make that clear.   I knew you did it, so it must be possible.  This lead me to Google for "calling BizTalk map in pipeline" and I did find this: https://code.msdn.microsoft.com/windowsdesktop/Executing-BizTalk-map-in-1b2aaf84 that might help.
